# -*- coding: utf-8 -*-
"""origen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113E1RiudEPgpsRV1Ah6IGoHkgyKDpNRF
"""

mi_caja=315486254
mi_texto="este es un texto creado en otro script"
nombre="Daniel"
edad=26
es_progrador=True

def yo_saludo():
  print("Hola, buenos días, han avanzado harto")

class Estudiantes:
  def __init__(self,nombre, correo):
    self.name=nombre
    self.mail=correo+"@unisabana.edu.co"

  def saludar(self):
    print("qué más")